{"uuid": "e682728e-aa1d-4277-bf72-b29fef1f4c33", "children": ["d71ae965-5c1b-4e0c-ab94-7163f675b9e0"], "befores": [{"name": "set_maverick_mode_all", "status": "broken", "statusDetails": {"message": "paramiko.ssh_exception.SSHException: No existing session\n", "trace": "  File \"/home/imgd/TIP/venv/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/imgd/TIP/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/imgd/TIP/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/imgd/TIP/wlan-testing/tests/e2e/interOp/conftest.py\", line 640, in set_maverick_mode_all\n    ap_ssh = get_apnos(access_point_info, sdk=\"2.x\")\n  File \"/home/imgd/TIP/wlan-testing/tests/../libs/apnos/apnos.py\", line 42, in __init__\n    client = self.ssh_cli_connect()\n  File \"/home/imgd/TIP/wlan-testing/tests/../libs/apnos/apnos.py\", line 82, in ssh_cli_connect\n    client.connect(self.ip, username=self.username, password=self.password,\n  File \"/home/imgd/TIP/venv/lib/python3.8/site-packages/paramiko/client.py\", line 412, in connect\n    server_key = t.get_remote_server_key()\n  File \"/home/imgd/TIP/venv/lib/python3.8/site-packages/paramiko/transport.py\", line 834, in get_remote_server_key\n    raise SSHException(\"No existing session\")\n"}, "start": 1640770682622, "stop": 1640770692640}], "start": 1640770682622, "stop": 1640770692838}