{"uuid": "bedf9818-121f-4367-bb8e-dccdc28d91f8", "children": ["856ae56f-8813-4ee9-9b87-dc91df6d4adb"], "befores": [{"name": "get_ap_logs", "status": "passed", "start": 1640773724500, "stop": 1640773737463}], "afters": [{"name": "get_ap_logs::collect_logs", "status": "broken", "statusDetails": {"message": "paramiko.ssh_exception.SSHException: No existing session\n", "trace": "  File \"/home/imgd/TIP/venv/lib/python3.8/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/home/imgd/TIP/wlan-testing/tests/conftest.py\", line 683, in collect_logs\n    ap_ssh = get_apnos(ap, pwd=\"../libs/apnos/\", sdk=\"2.x\")\n  File \"/home/imgd/TIP/wlan-testing/tests/../libs/apnos/apnos.py\", line 42, in __init__\n    client = self.ssh_cli_connect()\n  File \"/home/imgd/TIP/wlan-testing/tests/../libs/apnos/apnos.py\", line 82, in ssh_cli_connect\n    client.connect(self.ip, username=self.username, password=self.password,\n  File \"/home/imgd/TIP/venv/lib/python3.8/site-packages/paramiko/client.py\", line 412, in connect\n    server_key = t.get_remote_server_key()\n  File \"/home/imgd/TIP/venv/lib/python3.8/site-packages/paramiko/transport.py\", line 834, in get_remote_server_key\n    raise SSHException(\"No existing session\")\n"}, "start": 1640775114305, "stop": 1640775124325}], "start": 1640773724500, "stop": 1640775124325}