{"uuid": "b8315627-4f52-44a7-b494-7dfe78b40e6d", "children": ["515dfbca-dbc0-4c81-b9d1-8f81f19a0075"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "paramiko.ssh_exception.SSHException: No existing session\n", "trace": "  File \"/home/imgd/TIP/venv/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/imgd/TIP/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/imgd/TIP/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/imgd/TIP/wlan-testing/tests/e2e/interOp/conftest.py\", line 228, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_ref,\n  File \"/home/imgd/TIP/wlan-testing/tests/fixtures_2x.py\", line 570, in setup_profiles\n    ap_ssh = get_apnos(get_configuration['access_point'][0], pwd=\"../libs/apnos/\", sdk=\"2.x\")\n  File \"/home/imgd/TIP/wlan-testing/tests/../libs/apnos/apnos.py\", line 42, in __init__\n    client = self.ssh_cli_connect()\n  File \"/home/imgd/TIP/wlan-testing/tests/../libs/apnos/apnos.py\", line 82, in ssh_cli_connect\n    client.connect(self.ip, username=self.username, password=self.password,\n  File \"/home/imgd/TIP/venv/lib/python3.8/site-packages/paramiko/client.py\", line 412, in connect\n    server_key = t.get_remote_server_key()\n  File \"/home/imgd/TIP/venv/lib/python3.8/site-packages/paramiko/transport.py\", line 834, in get_remote_server_key\n    raise SSHException(\"No existing session\")\n"}, "start": 1639482085013, "stop": 1639482095031}], "start": 1639482085013, "stop": 1639482095231}