{"uuid": "7526b7c5-7ba0-476f-845d-138963e010ad", "children": ["300dca06-88a5-4fa5-bdbf-064d31005409"], "befores": [{"name": "get_ap_logs", "status": "broken", "statusDetails": {"message": "paramiko.ssh_exception.SSHException: No existing session\n", "trace": "  File \"/home/imgd/TIP/venv/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/imgd/TIP/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/imgd/TIP/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/imgd/TIP/wlan-testing/tests/conftest.py\", line 678, in get_ap_logs\n    ap_ssh = get_apnos(ap, pwd=\"../libs/apnos/\", sdk=\"2.x\")\n  File \"/home/imgd/TIP/wlan-testing/tests/../libs/apnos/apnos.py\", line 42, in __init__\n    client = self.ssh_cli_connect()\n  File \"/home/imgd/TIP/wlan-testing/tests/../libs/apnos/apnos.py\", line 82, in ssh_cli_connect\n    client.connect(self.ip, username=self.username, password=self.password,\n  File \"/home/imgd/TIP/venv/lib/python3.8/site-packages/paramiko/client.py\", line 412, in connect\n    server_key = t.get_remote_server_key()\n  File \"/home/imgd/TIP/venv/lib/python3.8/site-packages/paramiko/transport.py\", line 834, in get_remote_server_key\n    raise SSHException(\"No existing session\")\n"}, "start": 1639118092098, "stop": 1639118102112}], "start": 1639118092098, "stop": 1639118102160}